# Generated by Django 6.0.7 on 2026-07-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='aboutme',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='architecture_notes',
            field=models.TextField(blank=True, help_text='DEV: Problem, Architecture, Key Decisions. Leave blank for Design Projects.'),
        ),
        migrations.AddField(
            model_name='projects',
            name='design_role',
            field=models.CharField(blank=True, help_text="Design: e.g. 'Brand Identity, UI/UX'. Leave blank for DEV projects.", max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines display order in the portfolio'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='credential_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_image',
            field=models.ImageField(upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skills'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='event_type',
            field=models.CharField(choices=[('Education', 'Education'), ('Experience', 'Experience'), ('Certification', 'Certification')], default='Experience', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projects')),
            ],
        ),
    ]
