# Generated by Django 6.0.7 on 2026-07-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_timeline_options_aboutme_github_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['stage', 'order']},
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='description',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='available_for_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='stage',
            field=models.CharField(choices=[('PROC', 'Process'), ('FIN', 'Final')], default='FIN', max_length=4),
        ),
        migrations.AddField(
            model_name='skills',
            name='icon_slug',
            field=models.CharField(blank=True, help_text="Simple Icons slug (e.g. 'tailwindcss', 'react'). Leave blank to auto-detect from name.", max_length=50),
        ),
        migrations.AddField(
            model_name='timeline',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if ongoing', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.projects'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='event_type',
            field=models.CharField(choices=[('Education', 'Education'), ('Experience', 'Experience'), ('Certification', 'Certification'), ('Leadership', 'Leadership')], default='Experience', max_length=50),
        ),
    ]
