# Generated by Django 6.0.7 on 2026-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_blogpost_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='twitter_link',
            new_name='x_link',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='medium_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='substack_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
