# Generated by Django 6.0.7 on 2026-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_twitter_link_aboutme_x_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
