# Generated by Django 6.0.7 on 2026-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Full Stack Development', 'Fullstack'), ('Frontend Development', 'Frontend'), ('Backend Development', 'Backend'), ('Design', 'Design'), ('AI Integration', 'Ai')], default='Full Stack Development', max_length=50),
        ),
    ]
