# Generated by Django 6.0.7 on 2026-09-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_projects_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_time_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
